apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmp-cm
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: my-plugin
    spec:
      version: v5.0
      init:
        command: [sh, -c, 'echo "Initializing..."']
      generate:
        command: [sh, -c, 'kubectl create cm $ARGOCD_APP_SOURCE_PATH --from-file=. --dry-run=client -o yaml']
