apiVersion: apps/v1
kind: Deployment
metadata:
  name: liquibase
  namespace: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: liquibase
  template:
    metadata:
      labels:
        app: liquibase
    spec:
      containers:
      - name: liquibase
        image: liquibase/liquibase:latest
        env:
        - name: JAVA_OPTS
          value: "-Dliquibase.hub.mode=off"
        volumeMounts:
        - name: liquibase-config
          mountPath: /liquibase/changelog
        command: ["sh", "-c"]
        args:
        - |
          cp /liquibase/changelog/liquibase.properties /liquibase/
          cp /liquibase/changelog/db.changelog-master.yaml /liquibase/
          liquibase --defaultsFile=/liquibase/liquibase.properties update
      volumes:
      - name: liquibase-config
        configMap:
          name: liquibase-config
